### PR TITLE
fix: install.sh might break python environments

### LINKED ISSUE #1133: macOS install.sh: Consider checking for python3.10 already installed
https://github.com/elebumm/RedditVideoMakerBot/blob/3eff3e438636f04fff30ecb4fecdf647c3e7a691/install.sh#L65

This line in install.sh can seriously screw up a python environment if python is already installed. On some versions of macOS (>10.15 IIRC) python3.10 is already installed.

Something like `if [ ! command -v brew &> /dev/null ]; then` in the install.sh may work. (this line is from the Homebrew install checker)

### PR DESCRIPTION
**Pull request by BlockArchitech**
# Description

Fixes an issue that might break python environments on macOS.

# Issue Fixes

Fixes #1133 

# Checklist:

- [x] I am pushing changes to the **develop** branch
- [x] I am using the recommended development environment
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas [N/A]
- [ ] I have formatted and linted my code using python-black and pylint [N/A]
- [ ] I have cleaned up unnecessary files [N/A]
- [x] My changes generate no new warnings
- [x] My changes follow the existing code-style
- [x] My changes are relevant to the project

# Any other information (e.g how to test the changes)

Test the changes on a macOS 10.15 or higher system as follows:

```bash
$ chmod +x install.sh
$ ./install.sh -l (or equivalent option)
```

## Sidenote

Been a while since I looked at this. New maintainers definitely are doing a great job!

### CODE REVIEW

File: install.sh [hunk 1]
```diff
@@ -62,7 +62,13 @@ function install_macos(){
     fi
     # Install the required packages
     echo "Installing required Packages" 
-    brew install python@3.10 tcl-tk python-tk
+    if [! commad --version python3 &> /dev/null ]; then
```
Comment (callumio) [inline install.sh:65]: I could be wrong, but should this not be command not commad?

If not dw, just looks like a spelling mistake to me

**Comment by BlockArchitech** [comment]
Alright @callumio - sorry about that 😅

When copying over this commit to GitHub because my git cli wasn't working, must of missed that.

**Review by JasonLovesDoggo — APPROVED** [review]
Lgtm
